# Generated by Django 2.1.1 on 2018-12-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=220)),
                ('title_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=220)),
                ('contact', models.CharField(max_length=220)),
            ],
        ),
    ]
