# Generated by Django 2.1.1 on 2018-12-29 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181229_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumbotron',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jumbotron',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
