# Generated by Django 2.1.1 on 2016-02-11 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181229_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='headings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
